### ISSUE TITLE
Use generally agreed on`.JuliaFormatter.toml` with formatting check GitHub action for org packages

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/SciMLStyle#2]
Not high priority and probably even a bad idea since people have their own opinions on formatting, but might be interesting?

**Comment by ChrisRackauckas** [comment]
Yes, it would be good to get a formatter toml that corresponds to these rules and get that rolled out for all of SciML. The default one has a BlueStyle rule which leads to some very difficult to read code (https://github.com/SciML/SciMLStyle/issues/3) which is why I don't use the formatter today, so I'd be happy if someone could help modify it a bit.

**Comment by YingboMa** [comment]
https://github.com/domluna/JuliaFormatter.jl/pull/588
