### ISSUE TITLE
How many indents to use for multi-line expressions?

### ISSUE THREAD

**Issue by xtalax** [SciML/SciMLStyle#3]
Should the guideline be "whatever looks neatest" or should this be limited to a single indent above the level of the first line, or something else?

In particular for array comprehensions and generators, and other non function call multi-line expressions.

**Comment by ChrisRackauckas** [comment]
Yeah I'm not sure what the rule is. Align with the `(` and keep it within the character limit (but fill lines as much as possible)? Like:

```julia
function my_large_function(argument1, argument2,
                                             argument3, argument4,
                                             argument5,x,y,z)
```

BlueStyle says if it goes over 92 then every argument is its own line:

```julia
function my_large_function(argument1, 
                                             argument2,
                                             argument3, 
                                             argument4,
                                             argument5,
                                             x,
                                             y,
                                             z)
```

but IMO that can make code with a lot of arguments very hard to read because it can just not even fit in the screen (see https://github.com/SciML/Sundials.jl/blob/master/src/common_interface/solve.jl#L358-L512), so I am pretty PO'd that the formatter keeps trying to force that by default even though it makes singles lines of code larger than my entire laptop screen. Basically, if you want to do that rule, you essentially are saying everyone should have a vertical monitor 😅. Use the space you have, code should be denser than that.
